name: CreaturePolicy
version: @VERSION@
description: Creature spawn control based on rules
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/CreaturePolicy
main: edgruberman.bukkit.creaturepolicy.Main
commands:
    'creaturepolicy:reload':
        description: Reload CreaturePolicy plugin
        permission: creaturepolicy.reload
        usage: /<command>
permissions:
    creaturepolicy.reload:
        description: Can use reload command
        default: op